"""Every probe the two independent reviews of #1128 wrote against the guard, verbatim.

They are answers in the old, free-text form (numbers and outcomes in the model's own words). Under
the placeholder design every one of them must be refused: the model may not write a digit, an
outcome or a decision itself. `test_guard.py` asserts that for each.
"""

from __future__ import annotations

#: (text, citations the probe named, evidence the probe named)
REVIEW_PROBES: list[tuple[str, tuple[str, ...], tuple[str, ...]]] = [
    ("Pages 4,9 look right [[0]][[1]].", ("C1", "C3"), ()),
    ("Page 4 & page 9 look right [[0]][[1]].", ("C1", "C3"), ()),
    ("Page 4 as well as page 9 looks right [[0]][[1]].", ("C1", "C3"), ()),
    ("Page 4 looks right whereas page 9 needs correction [[0]][[1]].", ("C1", "C3"), ()),
    ("Page 4 looks right while page 9 needs correction [[0]][[1]].", ("C1", "C3"), ()),
    ("Page 4 (like page 9 [[1]]) looks right [[0]].", ("C1", "C3"), ()),
    ("All three countertops need correction [[0]][[1]][[2]].", ("C1", "C2", "C3"), ()),
    ("Page 4 was confirmed by the reviewer [[0]][[1]].", ("C1", "C3"), ()),
    ("Page 4 looks right [[0]] [[1]].", ("C1", "C3"), ()),
    ("Page 4 needs correction [[0]]. It looks right now [[1]].", ("C1", "C3"), ()),
    ("Page 4 needs correction [[0]]. The other one needs correction too [[1]].", ("C1", "C3"), ()),
    ("Run A looks right [[0]].", ("C3",), ()),
    ("The fourth page looks right [[0]].", ("C3",), ()),
    ("Page three looks right [[0]].", ("C3",), ()),
    ("Page two needs correction [[0]].", ("C1",), ()),
    ("Page 3 looks right.", (), ("no_countertop_pages",)),
    ("Page 9 needs correction.", (), ("rows_not_checked",)),
    ("3 countertops look right.", (), ("blockers",)),
    ("All 3 countertops look right.", (), ("blockers",)),
    ("0 countertops need correction.", (), ()),
    ("Zero countertops need correction.", (), ()),
    ("Only 1 item needs your decision before sign-off.", (), ()),
    ("1 item needs your decision.", ("C1", "C2"), ()),
    ("A correction is not required for page 4 [[0]].", ("C1",), ()),
    ("No correction is needed on page 4 [[0]].", ("C1",), ()),
    ("Page 4 has been cleared [[0]].", ("C1",), ()),
    ("Page 4 is good to go [[0]].", ("C1",), ()),
    ("Nothing is wrong with page 4 [[0]].", ("C1",), ()),
    ("Page 4 is acceptable [[0]].", ("C1",), ()),
    ("Page 4 checks out [[0]].", ("C1",), ()),
    ("Page 4 is in spec [[0]].", ("C1",), ()),
    ("Page 4 meets the requirement [[0]].", ("C1",), ()),
    ("Page 4 is approved by the checks [[0]].", ("C1",), ()),
    ("Page 4 probably passes [[0]].", ("C1",), ()),
    ("Page 4 will pass once the vendor fixes it [[0]].", ("C1",), ()),
    ("Page 4 is good [[0]].", ("C1",), ()),
    ("Page 4 is all good [[0]].", ("C1",), ()),
    ("Page 4 adds up [[0]].", ("C1",), ()),
    ("Page 4 is accurate [[0]].", ("C1",), ()),
    ("Page 4 is valid [[0]].", ("C1",), ()),
    ("Page 4 conforms [[0]].", ("C1",), ()),
    ("Page 4 lines up [[0]].", ("C1",), ()),
    ("Page 4 is spot on [[0]].", ("C1",), ()),
    ("Page 4 has no issues [[0]].", ("C1",), ()),
    ("Page 4 has no problems [[0]].", ("C1",), ()),
    ("Page 4 is green [[0]].", ("C1",), ()),
    ("Page 4 succeeded [[0]].", ("C1",), ()),
    ("Page 4 is OK'd [[0]].", ("C1",), ()),
    ("Page 4 was corrected by the vendor [[0]].", ("C1",), ()),
    ("Page 4 has been fixed [[0]].", ("C1",), ()),
    ("Page 4 was resolved [[0]].", ("C1",), ()),
    ("Page 4 is settled [[0]].", ("C1",), ()),
    ("Page 4 was closed by the reviewer [[0]].", ("C1",), ()),
    ("Page 4 was signed [[0]].", ("C1",), ()),
    ("The reviewer already okayed page 4 [[0]].", ("C1",), ()),
    ("Page 4 got the green light [[0]].", ("C1",), ()),
    ("Page 4 needs correction? Not really [[0]].", ("C1",), ()),
    ("Does page 4 fail? It does not [[0]].", ("C1",), ()),
    ("Does page 4 need correction? No [[0]].", ("C1",), ()),
    ("Nothing on page 4 fails [[0]].", ("C1",), ()),
    ("None of page 4 is wrong [[0]].", ("C1",), ()),
    ("Page 4 fails nothing [[0]].", ("C1",), ()),
    ("Page 4 is without failures [[0]].", ("C1",), ()),
    ("Page 4 lacks any failure [[0]].", ("C1",), ()),
    ("Page 4 is free of failures [[0]].", ("C1",), ()),
    ("Page 4 hardly fails [[0]].", ("C1",), ()),
    ("Page 4 fails \u2014 not [[0]].", ("C1",), ()),
    ("Page 4 would fail if it were wrong, which it is not [[0]].", ("C1",), ()),
    ("Page 4 used to fail [[0]].", ("C1",), ()),
    ("Page 4 fails? Wrong [[0]].", ("C1",), ()),
    ("Page 4 is wrongly marked as failing [[0]].", ("C1",), ()),
    ("Page 4 is far from wrong [[0]].", ("C1",), ()),
    ("Calling page 4 wrong would be a mistake [[0]].", ("C1",), ()),
    ("The engine says page 4 needs correction, but it is a false alarm [[0]].", ("C1",), ()),
    ("Page 4 needs correction, though this is likely a reading error [[0]].", ("C1",), ()),
    ("Page 4 is flagged in error [[0]].", ("C1",), ()),
    ("Page 4 only needs correction on paper [[0]].", ("C1",), ()),
    ("Page 9 is anything but correct [[0]].", ("C3",), ()),
    ("Page 9 is far from fine [[0]].", ("C3",), ()),
    ("Page 9 looks right, supposedly [[0]].", ("C3",), ()),
    ("Page 9 looks right but is actually off [[0]].", ("C3",), ()),
    ("Page 9 seems to match, yet it is off [[0]].", ("C3",), ()),
    ("Page 9 looks right only by luck [[0]].", ("C3",), ()),
    ("Page 9 looks right, in theory [[0]].", ("C3",), ()),
    ("Page 9 is fine; I would still reject it [[0]].", ("C3",), ()),
    ("Page 9 looks right so you should approve it [[0]].", ("C3",), ()),
    ("Page 9 looks right, so go ahead and approve it [[0]].", ("C3",), ()),
    ("You can approve page 9 [[0]].", ("C3",), ()),
    ("Page 9 is ready for approval [[0]].", ("C3",), ()),
    ("Page 9 needs fixing [[0]].", ("C3",), ()),
    ("Page 9 has an error [[0]].", ("C3",), ()),
    ("Page 9 is off [[0]].", ("C3",), ()),
    ("Page 9 is broken [[0]].", ("C3",), ()),
    ("Page 9 is a problem [[0]].", ("C3",), ()),
    ("Page 9 is bad [[0]].", ("C3",), ()),
    ("Page 9 does not add up [[0]].", ("C3",), ()),
    ("Page 9 is non conforming [[0]].", ("C3",), ()),
    ("Page 9 is out of spec [[0]].", ("C3",), ()),
    ("Page 9 is too short [[0]].", ("C3",), ()),
    ("Page 9 has a discrepancy [[0]].", ("C3",), ()),
    ("Page 9 is inconsistent [[0]].", ("C3",), ()),
    ("Page 9 has an issue [[0]].", ("C3",), ()),
    ("Page 9 needs rework [[0]].", ("C3",), ()),
    ("Page 9 needs to be redrawn [[0]].", ("C3",), ()),
    ("Page 9 should be sent back to the vendor [[0]].", ("C3",), ()),
    ("Page 9 was rejected [[0]].", ("C3",), ()),
    ("The reviewer turned page 9 down [[0]].", ("C3",), ()),
    ('Page 4 prints 84 1/2" [[0]].', ("C1",), ()),
    ('Page 4 prints 85" [[0]].', ("C1",), ()),
    ('85" is printed on page 4 [[0]].', ("C1",), ()),
    ('84 1/2" is needed on page 4 [[0]].', ("C1",), ()),
    ('The needed overall on page 4 is 84 1/2" [[0]].', ("C1",), ()),
    ('Page 4 calls for 84 1/2" but shows 85" [[0]].', ("C1",), ()),
    ('The printed overall of 85" is short of the 84 1/2" needed [[0]].', ("C1",), ()),
    ('Page 4 is 1/2" too long [[0]].', ("C1",), ()),
    ('Page 4 is over by 1/2" [[0]].', ("C1",), ()),
    ('Page 4 is +1/2" [[0]].', ("C1",), ()),
    ('Page 4 is long by 1/2" [[0]].', ("C1",), ()),
    ('Piece 2 is 30" [[0]].', ("C1",), ()),
    ('The second piece is 30" [[0]].', ("C1",), ()),
    ('The middle piece is 18" [[0]].', ("C1",), ()),
    ('Piece #2 is 30" [[0]].', ("C1",), ()),
    ('Piece two is 30" [[0]].', ("C1",), ()),
    ('Pieces 1 and 2 are 36" and 30" [[0]].', ("C1",), ()),
    ('The pieces are 30", 30" and 18" [[0]].', ("C1",), ()),
    ('The pieces add up to 84" [[0]].', ("C1",), ()),
    ('The pieces add up to 85" [[0]].', ("C1",), ()),
    ('The pieces 30" + 36" + 18" make 84" [[0]].', ("C1",), ()),
    ('The field cut is 2" per end [[0]].', ("C1",), ()),
    ("There are 3 field cuts [[0]].", ("C1",), ()),
    ('The field cut is 1/2" at 3 ends [[0]].', ("C1",), ()),
    ('The tolerance is 1/2" [[0]].', ("C1",), ()),
    ('The tolerance is 2" [[0]].', ("C1",), ()),
    ('The difference is 3" [[0]].', ("C1",), ()),
    ('Page 4 is off by 2" [[0]].', ("C1",), ()),
    ('Page 4 is short by 2" [[0]].', ("C1",), ()),
    ('Page 4 is 2" short [[0]].', ("C1",), ()),
    ('Page 4 misses by 2" [[0]].', ("C1",), ()),
    ('Page 4 overall: 85" printed vs 84 1/2" required [[0]].', ("C1",), ()),
    ("Page 4's overall is 7'-1\" [[0]].", ("C1",), ()),
    ("Page 4 overall is 7 ft 1 in [[0]].", ("C1",), ()),
    ("Page 4 overall is 7 feet [[0]].", ("C1",), ()),
    ("The overall is eighty five inches printed [[0]].", ("C1",), ()),
    ("Printed: eighty-five inches [[0]].", ("C1",), ()),
    ("Printed overall 85 [[0]].", ("C1",), ()),
    ('Printed overall is 85" [[0]].', ("C1",), ()),
    ('The printed overall (85") [[0]].', ("C1",), ()),
    ('The overall printed, 85", is short [[0]].', ("C1",), ()),
    ('It was printed as 85" [[0]].', ("C1",), ()),
    ('The vendor drew 85" [[0]].', ("C1",), ()),
    ('The vendor wrote 85" [[0]].', ("C1",), ()),
    ('The vendor put 85" [[0]].', ("C1",), ()),
    ('The dimension on the drawing is 85" [[0]].', ("C1",), ()),
    ('Page 4 reads 85" [[0]].', ("C1",), ()),
    ('Expected 84 1/2" [[0]].', ("C1",), ()),
    ('Required: 84 1/2" [[0]].', ("C1",), ()),
    ('The target is 84 1/2" [[0]].', ("C1",), ()),
    ('The pieces need 84 1/2" [[0]].', ("C1",), ()),
    ("Page 4 has 4 pieces [[0]].", ("C1",), ()),
    ("Page 4 has 2 pieces [[0]].", ("C1",), ()),
    ("Page 4 has 30 pieces [[0]].", ("C1",), ()),
    ('Page 4 is 36" deep [[0]].', ("C1",), ()),
    ('The run is 18" wide [[0]].', ("C1",), ()),
    ('Page 4 overall: 84.50" [[0]].', ("C1",), ()),
    ('Page 4 overall: 84-1/2" [[0]].', ("C1",), ()),
    ('Page 4 overall: 84 \u00bd" [[0]].', ("C1",), ()),
    ("Page 4 overall: eighty four and one half inches [[0]].", ("C1",), ()),
    ("Page 4 overall: eighty-four and a half inches [[0]].", ("C1",), ()),
    ("Page 4 overall: 7'-0 1/2\" [[0]].", ("C1",), ()),
    ("Page 4 overall: 84 1/2 inches [[0]].", ("C1",), ()),
    ('Page 4 overall: 84\u00bd" [[0]].', ("C1",), ()),
    ('Page 4 overall: 169/2" [[0]].', ("C1",), ()),
    ('Page 4 overall: 84 2/4" [[0]].', ("C1",), ()),
    ('Page 4 is 0.5" short [[0]].', ("C1",), ()),
    ("Page 4 is a half inch short [[0]].", ("C1",), ()),
    ("Page 4 is 1/2 an inch short [[0]].", ("C1",), ()),
    ('Page 4 is about 1/2" short [[0]].', ("C1",), ()),
    ('Page 4 is roughly 85" [[0]].', ("C1",), ()),
    ('Page 4 is 84 1/2" \u00b1 1/2" [[0]].', ("C1",), ()),
    ('Page 4 is 1/2" in 85" [[0]].', ("C1",), ()),
    ("Page 4 is about 1% short [[0]].", ("C1",), ()),
    ("Page 4 is a half-percent short [[0]].", ("C1",), ()),
    ("Page 4 is 1.27 cm short [[0]].", ("C1",), ()),
    ("Page 4 is 12.7mm short [[0]].", ("C1",), ()),
    ("Page 4 is 12.7 millimetres short [[0]].", ("C1",), ()),
    ("Page 4 is 0.04 ft short [[0]].", ("C1",), ()),
    ("You can sign off now.", (), ("blockers",)),
    ("The package is ready for approval.", (), ("blockers",)),
    ("You may approve the package now.", (), ("blockers",)),
    ("Go ahead and approve the package.", (), ("blockers",)),
    ("There is no blocker left.", (), ("blockers",)),
    ("Sign-off is unblocked.", (), ("blockers",)),
    ("Nothing stands in the way of sign-off.", (), ("blockers",)),
    ("Every item has a decision.", (), ("blockers",)),
    ("All items are resolved.", (), ("blockers",)),
    ("No decisions are outstanding.", (), ("blockers",)),
    ("You're free to sign.", (), ("blockers",)),
    ("The package can be released.", (), ("blockers",)),
    ("Sign-off is available.", (), ("blockers",)),
    ("You are cleared to sign off.", (), ("blockers",)),
    ("Sign off whenever you like.", (), ("blockers",)),
    ("The review is complete.", (), ("blockers",)),
    ("The review is finished.", (), ("blockers",)),
    ("Everything has been reviewed.", (), ("blockers",)),
    ("Sign-off can go ahead.", (), ("blockers",)),
    ("There's nothing more to do.", (), ("blockers",)),
    ("Zero items need your decision.", (), ("blockers",)),
    ("0 items need your decision.", (), ("blockers",)),
    ("No items need your decision.", (), ("blockers",)),
    ("Nothing needs your decision.", (), ("blockers",)),
    ("None of the items need you.", (), ("blockers",)),
    ("Nothing is pending.", (), ("blockers",)),
    ("1 item needs your decision.", (), ("blockers",)),
    ("Only 2 items need your decision.", (), ("blockers",)),
    ("All 3 items look right.", (), ("blockers",)),
    ("3 items look right.", (), ("blockers",)),
    ("Everything looks right.", (), ("blockers",)),
    ("Every result looks right.", (), ("blockers",)),
    ("The whole package passes.", (), ("blockers",)),
    ("The package passes.", (), ("blockers",)),
    ("Nothing needs your decision.", (), ()),
    ("The package is ready for approval.", (), ()),
    ("Nothing needs your decision [[0]].", ("C3",), ()),
    ("Nothing is pending [[0]].", ("C2",), ()),
    ("See page 4 [[0]] at example.com/x.", ("C1",), ()),
    ("See ftp://x [[0]].", ("C1",), ()),
    ("**Page 4 needs correction** [[0]].", ("C1",), ()),
    ("# Page 4 [[0]]", ("C1",), ()),
    ("![x](y) [[0]]", ("C1",), ()),
    ("[click](javascript:alert(1)) [[0]]", ("C1",), ()),
    ("<img src=x onerror=alert(1)> [[0]]", ("C1",), ()),
    ("< img src=x> [[0]]", ("C1",), ()),
    ("&lt;script&gt; [[0]]", ("C1",), ()),
    ("Page 4 needs correction [[0]] \u202e thgir skool", ("C1",), ()),
    ("Page 4 needs correction [[0]] \u200b looks\u200bright", ("C1",), ()),
    ("Page 4 l\u043eoks right [[0]].", ("C1",), ()),
    ("Page 4 pa\u200bsses [[0]].", ("C1",), ()),
    ("Page 4 p-a-s-s-e-s [[0]].", ("C1",), ()),
    ("Page 4 PASSES [[0]].", ("C1",), ()),
    ("Page 4 passes\u0301 [[0]].", ("C1",), ()),
    ("Page \uff14 needs correction [[0]].", ("C3",), ()),
    ("Page \u0664 looks right [[0]].", ("C3",), ()),
    ("Page 4\u00a0looks right [[0]].", ("C3",), ()),
    ("Page\u00a04 looks right [[0]].", ("C3",), ()),
    ("Page 4 [[0]]: looks right.", ("C3",), ()),
    ("Page [[0]] 4 looks right.", ("C3",), ()),
    ("Page 4 needs correction [[ 0 ]].", ("C1",), ()),
    ("Page 4 needs correction [[00]].", ("C1",), ()),
    ("Page 4 needs correction [[0]]]].", ("C1",), ()),
    ("Page 4 needs correction [0].", ("C1",), ()),
    ("Page 4 needs correction [[\u0660]].", ("C1",), ()),
    ("Page 4 needs correction [[0]]", ("C1", "C1"), ()),
    (
        "The two AIs picked different countertop lines on this page, so nothing was read. Page 4 looks right [[0]].",
        ("C1", "C2"),
        (),
    ),
    ("Page 4 [[0]]: Both AIs found no stone countertop line on this sheet.", ("C1",), ()),
    ("Page 9 [[0]]: It matches.", ("C1",), ()),
    ("Page 4: It matches. [[0]]", ("C1",), ()),
    ("Page 4 [[0]]: confirmed by the reviewer.", ("C1",), ()),
    (
        "3 findings still need a valid reviewer decision or a check rerun after correction. Add a note when required.",
        ("C1",),
        (),
    ),
    (
        "Page 4 fails: 3 findings still need a valid reviewer decision or a check rerun after correction. [[0]]",
        ("C3",),
        (),
    ),
    ("Page 9: confirmed by the reviewer, and approved [[0]].", ("C3",), ()),
    ("Page 9 was confirmed by the reviewer and signed off [[0]].", ("C3",), ()),
    ("Page 9 was confirmed by the reviewer, so you can sign off [[0]].", ("C3",), ()),
    ("Sample run C looks right [[0]].", ("C1", "C3"), ()),
    ("Sample run A looks right [[0]][[1]].", ("C1", "C3"), ()),
    ("P4 looks right [[0]].", ("C3",), ()),
    ("C1 looks right [[0]].", ("C3",), ()),
    ("Pg.4 looks right [[0]].", ("C3",), ()),
    ("Page no. 4 looks right [[0]].", ("C3",), ()),
    ("Sheet A4 looks right [[0]].", ("C3",), ()),
    ("Page 9 of 4 looks right [[0]].", ("C3",), ()),
    ("Pages 9 and 4 look right [[0]].", ("C3",), ()),
    ("Pages 9, 4 look right [[0]].", ("C3",), ()),
    ("Pages 9 to 4 look right [[0]].", ("C3",), ()),
    (
        'Page 4 needs correction [[0]]. The printed overall is 84 1/2", but the pieces plus the field cut need 85" [[0]], a difference of -1/2" [[0]].',
        ("C1",),
        ("C1",),
    ),
    (
        'The countertop on page 4 needs correction because the printed overall does not match the pieces below it plus the field cut [[0]]. It prints 84 1/2" where 85" is needed [[0]].',
        ("C1",),
        ("C1",),
    ),
    (
        "Sign-off is not possible yet [[0]][[1]][[2]]. Three items still need your decision: page 4 needs correction [[0]], page 7 needs your decision [[1]], and the sink centre line check on page 5 is waiting on a value [[2]].",
        ("C1", "C2", "F1"),
        ("blockers",),
    ),
    (
        "You cannot sign off yet. 3 findings still need a valid reviewer decision or a check rerun after correction. They are on page 4 [[0]], page 7 [[1]] and page 5 [[2]].",
        ("C1", "C2", "F1"),
        ("blockers",),
    ),
    (
        "Page 3 has no countertop: both AIs found no stone countertop line on that sheet [[0]].",
        ("P3",),
        ("no_countertop_pages",),
    ),
    ("Only page 3 has no countertop [[0]].", ("P3",), ("no_countertop_pages",)),
    (
        "Page 7 needs your decision because the two AIs picked different countertop lines on this page, so nothing was read [[0]]. Open it in the queue to decide [[0]].",
        ("C2",),
        ("C2",),
    ),
    (
        "On page 7 the two AIs chose different countertop lines, so no measurement was taken and the result is held for you [[0]].",
        ("C2",),
        (),
    ),
    (
        "On page 4 the walls are the back wall and both ends, and that came from both readers, not from you [[0]].",
        ("C1",),
        (),
    ),
    (
        'On page 4 the printed overall is 84 1/2" [[0]]. The three pieces are 30", 36" and 18" [[0]], with a 1/2" field cut at each of the 2 ends [[0]].',
        ("C1",),
        ("C1",),
    ),
    (
        'Page 9 looks right [[0]]: printed 96", needed 96", difference 0" [[0]]. The decision was confirmed by the reviewer and carried over from the earlier run [[0]]. A second countertop on page 9 was not checked [[1]].',
        ("C3", "P9"),
        ("C3", "rows_not_checked"),
    ),
    (
        "Page 5 has the sink centre line check, which is waiting on a value [[0]]: the sink centre line is not given on this sheet, so the check could not run [[0]].",
        ("F1",),
        (),
    ),
    (
        "Of the three countertops, one needs correction (page 4) [[0]], one needs your decision (page 7) [[1]], and one looks right (page 9) [[2]].",
        ("C1", "C2", "C3"),
        (),
    ),
    (
        "Not yet. Sign-off is blocked until page 4 [[0]], page 7 [[1]] and the sink check on page 5 [[2]] have your decisions.",
        ("C1", "C2", "F1"),
        ("blockers",),
    ),
    (
        'The countertop width check on page 4 has a tolerance of 0" [[0]], so the -1/2" difference makes it need correction [[0]].',
        ("C1",),
        (),
    ),
    (
        "Page 4 needs correction because the printed overall does not match the pieces plus the field cut [[0]].",
        ("C1",),
        (),
    ),
    ('Page 4 is 1/2" short: it prints 84 1/2" but needs 85" [[0]].', ("C1",), ()),
    (
        "Two countertops need your decision: page 4 [[0]] and page 7 [[1]].",
        ("C1", "C2"),
        ("blockers",),
    ),
    ("One countertop needs correction, on page 4 [[0]].", ("C1",), ()),
    ("Page 9 looks right and needs nothing from you [[0]].", ("C3",), ()),
    ("Page 9 looks right; its decision was carried over from the earlier run [[0]].", ("C3",), ()),
    ('Page 9 looks right. Its printed overall of 96" matches the needed 96" [[0]].', ("C3",), ()),
    ("Page 7 was not measured because the two AIs picked different lines [[0]].", ("C2",), ()),
    ("On page 7 nothing was read, so there are no numbers to show [[0]].", ("C2",), ()),
    (
        "The architect check on page 7 was not compared because there is no countertop line [[0]].",
        ("C2",),
        (),
    ),
    (
        "Page 5 is waiting on a value: the sink centre line is not given on this sheet [[0]].",
        ("F1",),
        (),
    ),
    ('The first piece on page 4 is 30" wide [[0]].', ("C1",), ()),
    ('Page 4 has three pieces: 30", 36" and 18" [[0]].', ("C1",), ()),
    ('On page 4 the field cut is 1/2" per end, at both ends [[0]].', ("C1",), ()),
    ('The pieces on page 4 add up to 84", plus 1/2" at each end makes 85" [[0]].', ("C1",), ()),
    (
        "I can't find that in this review's records. Try opening page 4 on the drawing [[0]].",
        ("P4",),
        (),
    ),
    ("The records don't say who drew page 4 [[0]].", ("P4",), ()),
    (
        "Sign-off is not possible: 3 findings still need a decision [[0]][[1]][[2]].",
        ("C1", "C2", "F1"),
        ("blockers",),
    ),
    ("Page 9 has a second countertop that was not checked [[0]].", ("P9",), ("rows_not_checked",)),
    (
        "Page 9 looks right [[0]], but a second countertop there was not checked [[1]].",
        ("C3", "P9"),
        (),
    ),
]
