import assert from 'node:assert/strict';
import { documentListReducer as reduce, documentNavigation as nav, initialDocumentList } from '../src/pages/documentRows.js';
import type { DocumentRows } from '../src/pages/documentRows.js';

const first: DocumentRows = { rows: [], hasMore: true, nextCursor: 'opaque+/next=2' };
const last: DocumentRows = { rows: [], hasMore: false, nextCursor: null };
let state = reduce(initialDocumentList, { type: 'loaded', data: first });
assert.equal(nav(state).page, 1);
assert.equal(nav(state).previousDisabled, true);
assert.equal(nav(state).nextDisabled, false);
state = reduce(state, { type: 'next' });
assert.equal(state.data, first, 'old records stay visible while the page is in flight');
assert.deepEqual(state.requestedTrail, [undefined, 'opaque+/next=2'], 'never decode or fabricate a server cursor');
assert.equal(nav(state).page, 1, 'page number cannot advance before success');
assert.equal(nav(state).changingPage, true);
assert.equal(nav(state).nextDisabled, true);
assert.equal(reduce(state, { type: 'next' }), state, 'ignore double-click while pending');
state = reduce(state, { type: 'failed', error: '503 next page' });
assert.equal(state.data, first);
assert.equal(nav(state).page, 1);
const cursorToRetry = state.requestedTrail;
state = reduce(state, { type: 'loading' });
assert.equal(state.requestedTrail, cursorToRetry, 'retry requests the failed page, not page one');
state = reduce(state, { type: 'loaded', data: last });
assert.equal(nav(state).page, 2);
assert.equal(nav(state).nextDisabled, true, 'null, not the number of rows, marks the last page');
assert.equal(nav(state).previousDisabled, false, 'an empty later page can still navigate back');
assert.equal(nav(state).changingPage, false);
state = reduce(state, { type: 'previous' });
assert.deepEqual(state.requestedTrail, [undefined]);
assert.equal(nav(state).page, 2);
state = reduce(state, { type: 'failed', error: '503 previous page' });
assert.equal(state.data, last);
assert.equal(nav(state).page, 2, 'failed previous request keeps its current page');
state = reduce(state, { type: 'loading' });
state = reduce(state, { type: 'loaded', data: first });
assert.equal(nav(state).page, 1);
assert.equal(reduce(state, { type: 'previous' }), state);

state = reduce(state, { type: 'next' });
state = reduce(state, { type: 'loaded', data: first });
assert.equal(nav(state).repeatedCursor, true, 'a server cursor loop must not keep navigating forever');
assert.equal(nav(state).nextDisabled, true);
assert.equal(nav(state).previousDisabled, false);
assert.equal(reduce(state, { type: 'next' }), state);
console.log('document pagination: opaque cursors, previous/next, failure preservation, retry target, pending guards, empty final page and cycle protection passed');
