"""Seed one safe local demo package and check it for real.

**What this demonstrates, and what it does not.** The product's claim is *"the AI reads, exact
arithmetic decides, a reviewer signs off"*. The deciding half is built and tested; the reading half is
blocked on drawings (#274) and on semantic typing (Q20). This puts a person in the reading seat —
which `CLIENT_FACTS` Q7 already blesses: *"the reviewer types the values into input fields for that
drawing set"* — so the arithmetic runs against real numbers and produces real verdicts.

So: no extraction, no model, no drawing. Every number below is one somebody typed, and the findings
that come out are the engine's own, computed exactly.

**Every value here is illustrative and none is a default.** The parameters land in a *project* layer,
which is the sanctioned place for a per-project reviewer answer — not the company layer, and not a
rulebook default. `CLIENT_FACTS` Q2 has no tolerance from the client, Q21's filler bounds are
unsettled, and `CT-BACK-OFFSET-MIN-001` says in its own text that its minimum has no default because
the vendor value is pending. Nothing in this file may be read as a client value.

    python scripts/seed_demo.py                 # a reviewer-input package that passes
    python scripts/seed_demo.py --fail          # the same package with one dimension wrong
    python scripts/seed_demo.py --with-evidence # a synthetic uploaded drawing with a real crop

Prints the package id and every finding. Publish the rulebook first if the database has none:
`python scripts/run_checks.py <revision> --publish`.
"""

from __future__ import annotations

import argparse
import hashlib
import os
import pathlib
import sys
from collections.abc import Mapping
from datetime import UTC, datetime
from fractions import Fraction
from io import BytesIO
from typing import TYPE_CHECKING, Protocol
from uuid import UUID

if TYPE_CHECKING:
    from sqlalchemy.orm import Session

    from app.models import PackageRevision


class _DemoStages(Protocol):
    """The two real stages the seed deliberately demonstrates."""

    def run_checks(self, session: Session, package_revision_id: UUID) -> Mapping[str, object]:
        """Record the deterministic findings for the seeded revision."""

        ...

    def generate_outputs(self, session: Session, package_revision_id: UUID) -> Mapping[str, object]:
        """Build the reviewer handoff artifacts from the recorded findings."""

        ...


def _finish_seeded_review(
    session: Session, revision_id: UUID, stages: _DemoStages
) -> tuple[Mapping[str, object], Mapping[str, object]]:
    """Run the human-supplied demo through the same final hand-over as a real review.

    The seed has no uploaded drawings, so it starts where the reviewer-input path becomes
    deterministic checking. It must nonetheless record that checking and report generation ended
    before the package is presented for review; otherwise a completed demo says "Running checks"
    forever.
    """
    from app.lifecycle.states import transition
    from app.models import PackageState

    result = stages.run_checks(session, revision_id)
    transition(
        session,
        revision_id,
        PackageState.GENERATING_OUTPUTS,
        actor="demo seed",
        reason="the seeded reviewer inputs were checked",
    )
    outputs = stages.generate_outputs(session, revision_id)
    transition(
        session,
        revision_id,
        PackageState.AWAITING_REVIEW,
        actor="demo seed",
        reason="the seeded findings and handoff outputs are ready for reviewer sign-off",
    )
    return result, outputs


sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

#: The reviewer's own measurements, in inches, for one countertop assembly.
#:
#: `CT-DEPTH-001` computes `cabinet_depth + countertop_overhang` and compares it with the authored
#: shop depth, exactly — Q2 gives no tolerance, so the check is `equals` and 1/4" out is a FAIL.
CABINET_DEPTH = Fraction(24)
COUNTERTOP_OVERHANG = Fraction(3, 2)

#: What the reviewer read off the shop drawing. 25 1/2" agrees with 24 + 1 1/2 exactly.
SHOP_DEPTH_PASS = Fraction(51, 2)

#: A quarter inch out. Chosen because it is the shape of error this system exists to catch: a
#: plausible number, correctly read, that does not add up.
SHOP_DEPTH_FAIL = Fraction(101, 4)


def _synthetic_pdf(content: bytes) -> bytes:
    """Build the one-page synthetic fixture used only by the local evidence demo.

    This is deliberately a literal PDF rather than a copied drawing.  Its text is known, it contains
    no client material, and the crop the reviewer sees is generated by the ordinary evidence stage
    from these bytes.
    """
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 200 100] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
        b"<< /Length " + str(len(content)).encode() + b" >>\nstream\n" + content + b"\nendstream",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
    ]
    out = bytearray(b"%PDF-1.4\n")
    offsets: list[int] = []
    for number, body in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(number).encode() + b" 0 obj\n" + body + b"\nendobj\n"
    start = len(out)
    out += b"xref\n0 " + str(len(objects) + 1).encode() + b"\n0000000000 65535 f \n"
    for offset in offsets:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        b"trailer\n<< /Size "
        + str(len(objects) + 1).encode()
        + b" /Root 1 0 R >>\nstartxref\n"
        + str(start).encode()
        + b"\n%%EOF\n"
    )
    return bytes(out)


# This literal is a safe synthetic fixture, not a client drawing.  It deliberately differs by a
# quarter inch from the recorded synthetic project inputs (24 + 1 1/2 = 25 1/2), so the evidence
# viewer has a real, explainable FAIL to show.
EVIDENCE_LABEL = "641 [25 1/4]"
EVIDENCE_DRAWING = _synthetic_pdf(
    b"BT /F1 10 Tf 1 0 0 1 20 70 Tm (641 [25 1/4]) Tj ET\n"
    b"BT /F1 10 Tf 1 0 0 1 20 50 Tm (SYNTHETIC SHOP DEPTH) Tj ET\n"
)


def _project_depth_parameters(session: Session, revision: PackageRevision, now: datetime) -> None:
    """Store the explicitly labelled synthetic project inputs for the evidence demo."""
    from app.models import Package
    from app.models.parameters import to_rows
    from rules.parameters import ParameterLayer, ParameterSet, ParameterValue, Provenance
    from rules.schema import Quantity
    from units.measurement import Unit

    package = session.get(Package, revision.package_id)
    assert package is not None
    parameters = ParameterSet(
        project_id=str(package.project_id),
        layer=ParameterLayer.PROJECT,
        version=1,
        parameters={
            "cabinet_depth": ParameterValue(
                value=Quantity(value=CABINET_DEPTH, unit=Unit.INCH),
                provenance=Provenance.MEASURED,
                set_by="synthetic demo fixture",
                set_at=now,
            ),
            "countertop_overhang": ParameterValue(
                value=Quantity(value=COUNTERTOP_OVERHANG, unit=Unit.INCH),
                provenance=Provenance.MEASURED,
                set_by="synthetic demo fixture",
                set_at=now,
            ),
        },
    )
    stored, values = to_rows(parameters)
    session.add(stored)
    session.add_all(values)
    session.flush()


def _seed_evidence_demo(session: Session) -> tuple[UUID, UUID, Mapping[str, object]]:
    """Create one actual crop-backed finding using only a synthetic PDF.

    The extractor produces the raw candidate and the ordinary evidence stage cuts its crop.  The
    fixture then records one *explicit fixture confirmation* of ``CT010``; no model and no pipeline
    component assigns a semantic type.  This mirrors the reviewer action in the V1 loop while making
    a fresh local demo immediately inspectable.
    """
    from sqlalchemy import select
    from sqlalchemy.orm import sessionmaker

    from app.api.documents import storage_key
    from app.evidence.confirm import ConfirmationRefused, confirm_candidate_type
    from app.models import (
        Document,
        DocumentVersion,
        ObservationCandidate,
        Package,
        PackageRevision,
        PackageRevisionDocument,
        PackageState,
        Project,
        SourceArtifact,
    )
    from app.models.runs import WorkflowRun
    from storage.local import LocalStore
    from workflow.review import run_all
    from workflow.stages import DatabaseStages

    root = pathlib.Path(os.environ.get("GV_DEV_STORAGE", ".dev-storage")).resolve()
    store = LocalStore(root=root, ticket_secret=b"synthetic evidence demo fixture")
    now = datetime.now(UTC)
    project = Project(name="Synthetic evidence demo")
    session.add(project)
    session.flush()
    package = Package(project_id=project.id, vendor="Synthetic Fixture Vendor")
    session.add(package)
    session.flush()
    revision = PackageRevision(
        package_id=package.id, revision_number=1, state=PackageState.UPLOADED
    )
    session.add(revision)
    session.flush()

    digest = hashlib.sha256(EVIDENCE_DRAWING).hexdigest()
    document = Document(package_id=package.id, kind="shop")
    session.add(document)
    session.flush()
    key = storage_key(document.id, digest)
    source = SourceArtifact(storage_key=key, sha256=digest, size=len(EVIDENCE_DRAWING))
    session.add(source)
    session.flush()
    version = DocumentVersion(
        document_id=document.id,
        source_artifact_id=source.id,
        sha256=digest,
        page_count=1,
    )
    session.add(version)
    session.flush()
    session.add(
        PackageRevisionDocument(
            package_revision_id=revision.id,
            package_id=package.id,
            document_id=document.id,
            document_version_id=version.id,
        )
    )
    workflow_run = WorkflowRun(package_revision_id=revision.id, engine_run_id=str(revision.id))
    session.add(workflow_run)
    _project_depth_parameters(session, revision, now)
    store.put(key, BytesIO(EVIDENCE_DRAWING), content_type="application/pdf")
    session.commit()

    factory = sessionmaker(bind=session.get_bind(), expire_on_commit=False)
    run_all(
        factory,
        package_revision_id=revision.id,
        workflow_run_id=workflow_run.id,
        stages=DatabaseStages(store),
    )

    session.expire_all()
    candidate = session.execute(
        select(ObservationCandidate).where(
            ObservationCandidate.document_version_id == version.id,
            ObservationCandidate.raw_text == EVIDENCE_LABEL,
        )
    ).scalar_one_or_none()
    if candidate is None:
        raise RuntimeError(
            f"the synthetic fixture did not yield the expected raw candidate {EVIDENCE_LABEL!r}"
        )
    confirmed = confirm_candidate_type(
        session,
        candidate_id=candidate.id,
        semantic_type="CT010",
        confirmed_by="synthetic demo fixture (explicit CT010 confirmation)",
    )
    assert not isinstance(
        confirmed, ConfirmationRefused
    ), f"the fixture candidate could not be confirmed: {confirmed.detail}"

    stages = DatabaseStages(store)
    checks = stages.run_checks(session, revision.id)
    outputs = stages.generate_outputs(session, revision.id)
    session.commit()
    return package.id, revision.id, {"checks": checks, "outputs": outputs}


def main() -> int:
    """Seed one completed reviewer-input demo package and print its recorded findings."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--fail",
        action="store_true",
        help="supply a shop depth that is a quarter inch out, so the check FAILs",
    )
    parser.add_argument(
        "--with-evidence",
        action="store_true",
        help=(
            "seed a clearly labelled synthetic uploaded PDF, run the real crop pipeline, and "
            "create one fixture-confirmed CT010 finding for the evidence viewer"
        ),
    )
    args = parser.parse_args()

    from sqlalchemy import create_engine
    from sqlalchemy.orm import Session

    from app.config import Settings
    from app.models import Package, PackageRevision, PackageState, Project
    from app.models.parameters import to_rows
    from rules.parameters import (
        ParameterLayer,
        ParameterSet,
        ParameterValue,
        Provenance,
    )
    from rules.schema import Quantity
    from units.measurement import Measurement, Unit
    from verdict.operands import EvidenceStatus, VerdictOperand
    from workflow.stages import DatabaseStages

    settings = Settings()  # type: ignore[call-arg]
    engine = create_engine(settings.database_url)
    now = datetime.now(UTC)
    shop_depth = SHOP_DEPTH_FAIL if args.fail else SHOP_DEPTH_PASS

    with Session(engine) as session:
        if args.with_evidence:
            package_id, revision_id, result = _seed_evidence_demo(session)
            print(f"package  {package_id}")
            print(f"revision {revision_id}")
            print("fixture: synthetic uploaded shop PDF; no client drawing or reviewer annotation")
            print(f"fixture label: {EVIDENCE_LABEL} (25 1/4 in)")
            print("fixture confirmation: explicit CT010 fixture input; no model or auto-typing")
            print(f"checks: {dict(result['checks'])}")
            print(f"outputs: {dict(result['outputs'])}")
            print("status: ready for review with a real mechanical evidence crop")
            print()
            _print_findings(session, revision_id)
            return 0

        project = Project(name="Reviewer-supplied demo")
        session.add(project)
        session.flush()
        package = Package(project_id=project.id, vendor="Apex Glass & Stone")
        session.add(package)
        session.flush()
        revision = PackageRevision(
            package_id=package.id,
            revision_number=1,
            state=PackageState.RUNNING_CHECKS,
        )
        session.add(revision)
        session.flush()

        # The project's own settings, as a reviewer would enter them for this job. `Provenance.SPECIFIED`
        # says a person supplied it: `rules/parameters.py` refuses any provenance a model could claim.
        parameters = ParameterSet(
            project_id=str(project.id),
            layer=ParameterLayer.PROJECT,
            version=1,
            parameters={
                "cabinet_depth": ParameterValue(
                    value=Quantity(value=CABINET_DEPTH, unit=Unit.INCH),
                    # MEASURED: a person measured or read it. `HUMAN_PROVENANCES` is
                    # `{MEASURED, GC_CLIENT}` and no member exists that a model could claim — the
                    # vocabulary is what keeps a model's number out, not a check somewhere.
                    provenance=Provenance.MEASURED,
                    set_by="demo reviewer",
                    set_at=now,
                ),
                "countertop_overhang": ParameterValue(
                    value=Quantity(value=COUNTERTOP_OVERHANG, unit=Unit.INCH),
                    provenance=Provenance.MEASURED,
                    set_by="demo reviewer",
                    set_at=now,
                ),
            },
        )
        stored, values = to_rows(parameters)
        session.add(stored)
        for value in values:
            session.add(value)
        session.flush()

        # The reading, by a person. HUMAN_CONFIRMED is one of the two statuses the evidence gate
        # accepts, and it is the honest one here: a reviewer read this off the drawing, not the system.
        operands = {
            "CT-DEPTH-001": {
                "countertop_depth": VerdictOperand(
                    name="countertop_depth",
                    value=Measurement(shop_depth, Unit.INCH, str(shop_depth)),
                    status=EvidenceStatus.HUMAN_CONFIRMED,
                    source="SHOP",
                    evidence_ref="reviewer:typed",
                )
            }
        }

        # This seed enters at RUNNING_CHECKS because it deliberately demonstrates the
        # human-operated path after the reviewer has supplied the inputs above.  It still has to
        # walk the final two real lifecycle edges: leaving it at RUNNING_CHECKS once the findings
        # and report exist tells the reviewer work is ongoing when there is nothing left to wait
        # for.
        result, outputs = _finish_seeded_review(
            session, revision.id, DatabaseStages(operands=operands)
        )
        session.commit()

        print(f"package  {package.id}")
        print(f"revision {revision.id}")
        print(
            f"reviewer typed shop depth: {shop_depth} in   (expects {CABINET_DEPTH} + "
            f"{COUNTERTOP_OVERHANG} = {CABINET_DEPTH + COUNTERTOP_OVERHANG})"
        )
        print(f"checks: {dict(result)}")
        print(f"outputs: {dict(outputs)}")
        print("status: ready for review")
        print()
        _print_findings(session, revision.id)
    return 0


def _print_findings(session: Session, revision_id: UUID) -> None:
    """Every finding, read back out of the database rather than off this script's hopes.

    The join is on `RuleSnapshot.id`, not `snapshot_id`: `CheckRun.rule_snapshot_id` is the row's
    UUID while `snapshot_id` is the content hash as text. Comparing them asks PostgreSQL for
    `varchar = uuid` and it says so, which is how this was caught.
    """
    from sqlalchemy import select

    from app.models import CheckRun, Finding, RuleSnapshot
    from app.verdicts.rulebook import from_row

    rule_of_run: dict[UUID, str] = {}
    rows = session.execute(
        select(CheckRun, RuleSnapshot)
        .join(RuleSnapshot, RuleSnapshot.id == CheckRun.rule_snapshot_id)
        .where(CheckRun.package_revision_id == revision_id)
    ).all()
    for run, snapshot in rows:
        rule_of_run[run.id] = from_row(snapshot).rule.id

    for finding in session.execute(
        select(Finding).where(Finding.package_revision_id == revision_id)
    ).scalars():
        rule_id = rule_of_run.get(finding.check_run_id, "?")
        trace = finding.trace or {}
        why = trace.get("comparison") or trace.get("reason") or ""
        print(f"  {finding.outcome:16} {rule_id:26} {str(why)[:76]}")


if __name__ == "__main__":
    raise SystemExit(main())
