/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/operations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every operation a rule may name, with its signature
         * @description Every reviewed operation in the typed registry, in name order.
         *
         *     Read from `verdict.registry.REGISTRY` as it stands right now. Nothing in this module names an
         *     operation, so this endpoint cannot fall out of step with the engine: an operation the engine can
         *     run appears here, and one it cannot does not.
         *
         *     Each entry is a signature — a name, a version, whether it decides an outcome or derives an
         *     intermediate value, and what operands it takes. Not the implementation, and not a way to invoke
         *     one: this API never runs a check on request.
         */
        get: operations["list_operations_api_v1_operations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/accepted-work/{accepted_work_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What happened to work this API accepted
         * @description Whether accepted work has started, in plain English.
         *
         *     **`started` is not `finished`.** This reports what the outbox knows — that the workflow was handed
         *     to the engine — and nothing about the outcome. For the result, read the package or its findings.
         *
         *     Work belonging to another project is reported as not found, in the same words as work that does
         *     not exist. A 403 would confirm it exists, which is what the boundary is for.
         */
        get: operations["read_accepted_work_api_v1_projects__project_id__accepted_work__accepted_work_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/documents/{document_id}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Confirm an upload landed, and start ingestion
         * @description Check the bytes, then write the version and the ingestion request in one transaction.
         *
         *     In order:
         *
         *     1. The stored object for your declared hash must exist. Nothing there is `409` — there is no upload
         *        to confirm, which is different from a bad request.
         *     2. It is read and hashed. If it does not hash to what you declared, the request is refused with
         *        `422` and **nothing at all is written** — no artifact row, no version, no outbox row.
         *     3. The `SourceArtifact`, the `DocumentVersion` and the outbox row are written in one transaction.
         *        Either all three land or none do.
         *
         *     Returns `201` when a version was created and `200` when these exact bytes had already been
         *     confirmed. The repeat is a genuine no-op: the same version comes back and no second outbox row is
         *     written, so ingestion does not run twice.
         *
         *     Reading the object to hash it is the one piece of real work here, and it is bounded by the size of
         *     one drawing. It is also the only honest way to verify: `AGENTS.md` §2.7 pins a document version to
         *     exact bytes, and taking the client's word for the hash would make that pin a restatement of their
         *     claim. A backend that computes the checksum itself can answer this without a read; the local
         *     filesystem cannot, and #221 is where that becomes worth optimising.
         */
        post: operations["confirm_upload_api_v1_projects__project_id__documents__document_id__confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/documents/{document_id}/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Get an upload ticket for a new version of an existing document
         * @description A ticket for re-uploading this document — new bytes, same logical document.
         *
         *     This is the route that makes "a re-upload is a new version, never an edit" reachable through the
         *     API. The existing versions are untouched, and confirming these bytes inserts another
         *     `document_versions` row beside them.
         *
         *     Reads nothing and writes nothing: the document already exists, and the ticket is derived from its
         *     id and the hash you declared.
         */
        post: operations["request_upload_api_v1_projects__project_id__documents__document_id__uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List this project's packages, newest first
         * @description One page of this project's packages, newest first.
         *
         *     Pass the `next_cursor` from the previous page to continue. `next_cursor` is `null` on the last
         *     page, and that is the only reliable way to know you have reached it — a short page is not one.
         */
        get: operations["list_packages_api_v1_projects__project_id__packages_get"];
        put?: never;
        /**
         * Create a package and its first revision
         * @description Create a package in this project, in state `CREATED`, with revision 1.
         *
         *     Two checks, because they answer different questions: `require_project_access` says the caller may
         *     see this project at all, and `require_action` says creating a package is something their role may
         *     do. Collapsing them would make "any member of a project may create packages in it" true by
         *     accident rather than by decision.
         *
         *     The package, its first revision and the revision's birth event are one transaction. A package with
         *     no revision would be a package nothing can be uploaded to, and it would look completely normal in
         *     a list.
         *
         *     A project that does not exist answers `404`, in the same words as a project the caller is not in.
         */
        post: operations["create_package_api_v1_projects__project_id__packages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/packages/{package_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read one package
         * @description One package, or a `404` that cannot be told apart from the package not existing.
         */
        get: operations["get_package_api_v1_projects__project_id__packages__package_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/packages/{package_id}/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register a document and get an upload ticket
         * @description Create the document's identity and hand back where to send its bytes.
         *
         *     **No file in this request.** Hash your file locally, send the hash, and you get back a URL scoped
         *     to one storage key, permitting a write and nothing else, expiring at `expires_at`. Send the bytes
         *     there with the `method` and `required_headers` exactly as returned, then call `/confirm`.
         *
         *     The ticket is issued *before* the document row is committed, so a store that cannot issue one
         *     leaves no half-registered document behind. Nothing is written to storage either — a ticket is an
         *     intention, and an intention that is never used leaves nothing to clean up.
         */
        post: operations["register_document_api_v1_projects__project_id__packages__package_id__documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/packages/{package_id}/findings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List a package's findings, worst first
         * @description One page of this package's findings, worst first.
         *
         *     **Every outcome is included unless you ask for fewer.** The abstentions — `NOT_FOUND`,
         *     `REVIEW_REQUIRED`, `NO_APPLICABLE_RULE` — are things the engine concluded, and a default that
         *     hid them would report a package as clean on the strength of checks nobody looked at.
         *
         *     **Order:** severity worst-first, then outcome (failures, then abstentions, then passes), then
         *     oldest first, then id. The full description comes back in `ordering` on every page.
         *
         *     **Paging:** pass the `next_cursor` from the previous page. `next_cursor` is `null` on the last
         *     page. The cursor names the last row rather than counting rows, so findings written while you are
         *     paging cannot push a row across a page boundary and out of sight.
         *
         *     **Scope:** a package in another project is reported as not found, in the same words as a package
         *     that does not exist. That is deliberate — see `docs/DESIGN_PLATFORM.md` §4.3.
         *
         *     The response carries identity and versions, not calculation traces. Reconstructing a finding
         *     from its own operands is a per-finding request (`docs/DESIGN_PRODUCT.md` §3.1).
         */
        get: operations["list_findings_api_v1_projects__project_id__packages__package_id__findings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/packages/{package_id}/findings/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export a package's findings in a versioned shape
         * @description Every finding for one package, with its chain, labelled and counted.
         *
         *     The project boundary is established by the dependency and then again in SQL, the same belt-and-braces
         *     `finding_chain` uses: the dependency proves the caller may see the project, and the join proves these
         *     rows belong to it.
         *
         *     A package with no findings is an empty export, not a 404 — but it is only reached for a package that
         *     exists in this project, so "nothing found" cannot be confused with "no such package".
         */
        get: operations["export_findings_api_v1_projects__project_id__packages__package_id__findings_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/packages/{package_id}/findings/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How this package's findings break down
         * @description Counts per outcome for one package, so a list can show them without fetching every finding.
         *
         *     Built on `_base_query`, so the project boundary is the same one the list endpoint applies rather
         *     than a second query that could drift from it — and a package in another project is `404`, not an
         *     empty summary, because an empty summary would confirm the package exists.
         *
         *     **Every outcome is counted and they sum to the total.** Reporting only passes and failures would
         *     leave the abstentions uncounted and invite a reader to treat the remainder as passing. Under
         *     exact match those abstentions are the expected bulk of a run, not an edge case.
         *
         *     Counted in the database rather than by paging the findings and adding them up here: the control
         *     plane does short work only (`DESIGN_PLATFORM.md` §4.1), and a package with thousands of findings
         *     would otherwise turn a summary into the most expensive call in the API.
         */
        get: operations["summarise_findings_api_v1_projects__project_id__packages__package_id__findings_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/packages/{package_id}/findings/{finding_id}/chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Finding Chain
         * @description Return the stored chain, while preserving the project isolation boundary.
         */
        get: operations["finding_chain_api_v1_projects__project_id__packages__package_id__findings__finding_id__chain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/packages/{package_id}/review-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Open a review session over one package revision
         * @description Start a sitting. The reviewer is the caller, not a name in the body.
         *
         *     A revision outside this project is `404` rather than `403`, like everything else here: a 403
         *     would confirm it exists, and project scope is an isolation boundary rather than a filter.
         */
        post: operations["open_review_session_api_v1_projects__project_id__packages__package_id__review_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/review-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review sessions in this project, newest first
         * @description The sessions a reviewer picks up again — what the workspace sidebar lists.
         *
         *     `mine` defaults to true. A reviewer's own sittings are what they came back for, and a list
         *     defaulting to everyone's would bury them on any project with more than one reviewer.
         */
        get: operations["list_review_sessions_api_v1_projects__project_id__review_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/review-sessions/{review_session_id}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record what the reviewer did to one finding
         * @description Append one action. Never an edit — a changed mind is a second row and the first one stays.
         *
         *     The actor is the caller and the revision is read off the finding the service loads, so neither
         *     can be stated by the client. That is what "an action references a server-side finding revision"
         *     means in code rather than in a comment.
         */
        post: operations["record_review_action_api_v1_projects__project_id__review_sessions__review_session_id__actions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/projects/{project_id}/review-sessions/{review_session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Finish a review session
         * @description Close the sitting. Completing twice is refused rather than treated as a no-op — the second
         *     attempt means somebody believes they are finishing work that was already finished.
         */
        post: operations["complete_review_session_api_v1_projects__project_id__review_sessions__review_session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every published rule, with whether it could be released
         * @description Every rule in the rulebook, at its effective version, rule id order.
         *
         *     A rule whose tolerance is still a placeholder appears here like any other, and says plainly that
         *     it cannot be released. Leaving it out would make the rulebook look finished, which is exactly
         *     how a placeholder starts reading as a fact (ADR-0011).
         *
         *     Not paged. The collection is the rules GV has authored — tens of them, not thousands — and no
         *     API client can add to it, so a cursor would be machinery guarding against growth that this
         *     endpoint cannot experience.
         */
        get: operations["list_rules_api_v1_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/tolerance-report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * How much of the rulebook is still waiting on a client value
         * @description Which rules are still guesswork, and how many.
         *
         *     Declared before `/rules/{rule_id}/...` so the literal path cannot be shadowed by a rule id.
         *
         *     The prose comes from `rules/publication.py` unchanged, because it is written to be pasted into a
         *     client email without editing — a report only this codebase can read is not a report. The counts
         *     beside it come from `rules/governance/readiness.py`, so the numbers and the sentence cannot
         *     drift into describing different rulebooks.
         *
         *     Why this is an endpoint at all: the `±1/8″` figure that circulated for weeks was our own
         *     placeholder from a sample file, and it reached `docs/RULE_ENGINE_SPEC.md` §4 reading as fact.
         *     Nothing counted placeholders, so nothing contradicted the impression that the rulebook was
         *     finished.
         */
        get: operations["read_tolerance_report_api_v1_rules_tolerance_report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/applicability": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * What this rule applies to
         * @description The discriminator that selects a variant, and the tolerance each branch carries.
         *
         *     Reported for the effective version, because the question this answers is "what would this rule
         *     do to a drawing today?".
         *
         *     A rule that applies to everything of its product type says so explicitly (`scope: global`) — it
         *     does not simply have no variants. ADR-0007 refuses to read an absent applicability as "applies
         *     to everything", and this response keeps that distinction visible rather than flattening both
         *     cases into an empty list.
         */
        get: operations["read_applicability_api_v1_rules__rule_id__applicability_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish an approved proposal through the D6 gate
         * @description Approve and publish one proposal. Every decision is D6's.
         *
         *     This endpoint does four things and decides nothing: it maps the caller onto a rulebook approver,
         *     finds the proposal they named, calls `rules.governance.publish.publish()`, and turns whatever
         *     comes back — a snapshot or a refusal — into a response. There is no "already approved"
         *     shortcut, no override for a failed regression, and no path that writes a snapshot without going
         *     through that call.
         *
         *     **Who may.** `Action.PUBLISH_RULE` from the permission table, and then a rulebook role. The two
         *     are different questions and both are asked. A caller the API permits but the rulebook has no
         *     role for is refused with `403` rather than approximated — see `GOVERNANCE_ROLES`.
         *
         *     **Which proposal.** Named by the content hash it would publish as. The hash changes the moment
         *     the proposed rule does, so approving one is approving the exact bytes that were read.
         *
         *     **What each refusal means.**
         *
         *     | Status | Reason |
         *     |---|---|
         *     | `403` | The caller may not publish, or may not approve this particular proposal (they raised it). |
         *     | `404` | No such proposal for this rule. |
         *     | `409` | The proposal did not validate, its tolerance is unconfirmed and the target is production, the regression failed, or this content is already published. |
         *
         *     Every one of those carries D6's own explanation. Replacing them with a generic message would
         *     send an author looking for a fault in their rule when the real problem is that they are not
         *     allowed to publish at all.
         */
        post: operations["publish_rule_api_v1_rules__rule_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rules/{rule_id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Every published version of one rule, newest first
         * @description Every snapshot of this rule, each with its content hash and the bytes behind it.
         *
         *     Superseded versions stay listed. A finding cites the snapshot that produced it, and answering
         *     "what did you tell us in March?" means being able to read the rule as it was in March.
         *
         *     Each entry carries `canonical_json` in full so the hash can actually be checked. That costs a
         *     few kilobytes per version and buys the client the ability to confirm they received what the
         *     identifier names; a hash returned without the bytes it covers is decoration.
         */
        get: operations["list_snapshots_api_v1_rules__rule_id__snapshots_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description The process is alive. Says nothing about whether it can work — see `/ready`.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ready
         * @description The process can do work: the database answers and the schema is **at head**.
         *
         *     Returns 503 rather than raising, because a readiness probe that 500s is indistinguishable from
         *     a crashed process, and the two call for different responses from an orchestrator.
         *
         *     The migration check is the part that matters, and the first version did not do what this
         *     docstring claimed. It asked only whether `alembic_version` was non-empty, so a database three
         *     migrations behind answered `200 ready` — exactly the failure the endpoint exists to catch. It
         *     now compares the applied revision against the head revision in `alembic/versions`.
         *
         *     The work runs in a worker thread: `create_engine` and a synchronous session block the event
         *     loop, and a readiness probe that stalls it makes every other request slow while reporting on
         *     health.
         */
        get: operations["ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AbstentionTraceOut
         * @description Why nothing was calculated.
         *
         *     A real and separate shape, not a degenerate calculation: `app/budget/overflow.py` writes one when
         *     a package exhausts its model budget, and it carries a cause and a reason rather than operands.
         *     Reporting it as an empty calculation would render an abstention as a check that ran and found
         *     nothing, which is the reading V1 must never invite.
         */
        AbstentionTraceOut: {
            /** Cause */
            cause: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "abstention";
            /**
             * Reason
             * @default
             */
            reason: string;
            /** Regions Done */
            regions_done?: number | null;
            /** Review Complete */
            review_complete?: boolean | null;
        };
        /**
         * AcceptedOut
         * @description What an endpoint returns when it has accepted work rather than done it.
         *
         *     Carries no result and no estimate. There is nothing truthful to say about either at this point,
         *     and a hopeful one would be read as a promise.
         */
        AcceptedOut: {
            /**
             * Accepted Work Id
             * Format: uuid
             */
            accepted_work_id: string;
            /**
             * Status
             * @default queued
             */
            status: string;
            /** Status Url */
            status_url: string;
            /**
             * What It Means
             * @default Recorded and waiting. Nothing has started yet — the work is committed to happen, and a dispatcher has not picked it up.
             */
            what_it_means: string;
        };
        /**
         * ApplicabilityOut
         * @description What a rule applies to: one discriminator and its branches, or everything of its type.
         */
        ApplicabilityOut: {
            /**
             * Discriminator
             * @description The field that selects a variant, e.g. `wall_config`.
             */
            discriminator?: string | null;
            /** Rule Id */
            rule_id: string;
            /**
             * Scope
             * @description `global` when the rule applies to every item of its product type, otherwise `discriminated`. A rule with no discriminator has to say so — ADR-0007 refuses to read an absent applicability as 'applies to everything'.
             */
            scope: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Variants */
            variants?: components["schemas"]["ApplicabilityVariantOut"][];
            /** Version */
            version: string;
        };
        /**
         * ApplicabilityVariantOut
         * @description One branch of a rule's discriminator, e.g. `when: back_left_right`.
         */
        ApplicabilityVariantOut: {
            /**
             * Tolerance
             * @description The exact authored tolerance as text — `1/8 in`, `UNCONFIRMED` when the client has not supplied one, or null when this exact-equality operation uses no tolerance. A string rather than a number on purpose: `1/8` is a fraction, and rendering it as 0.125 would put a float in the one place this project refuses to.
             */
            tolerance: string | null;
            /**
             * Tolerance Confirmed
             * @description Null when no tolerance applies; otherwise whether its value is confirmed.
             */
            tolerance_confirmed: boolean | null;
            /** When */
            when: string;
        };
        /**
         * AwaitingToleranceOut
         * @description One rule that cannot be released, and how much of it is still a guess.
         */
        AwaitingToleranceOut: {
            /** Rule Id */
            rule_id: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Unconfirmed */
            unconfirmed: number;
            /** Version */
            version: string;
        };
        /**
         * CalculationTraceOut
         * @description The arithmetic, when arithmetic ran. Mirrors `verdict.trace.CalculationTrace`.
         */
        CalculationTraceOut: {
            /** Arithmetic Unit */
            arithmetic_unit?: string | null;
            /**
             * Comparison
             * @default
             */
            comparison: string;
            /**
             * Engine Version
             * @default
             */
            engine_version: string;
            /**
             * Intermediates
             * @default []
             */
            intermediates: [
                string,
                string
            ][];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "calculation";
            /**
             * Operands
             * @default []
             */
            operands: components["schemas"]["TracedOperandOut"][];
            /** Operation */
            operation: string;
            /**
             * Operation Version
             * @default
             */
            operation_version: string;
            /**
             * Outcome
             * @default
             */
            outcome: string;
            /** Tolerance */
            tolerance?: string | null;
        };
        /**
         * DocumentKind
         * @description Kinds of versioned source document accepted by the V1 ingestion path.
         * @enum {string}
         */
        DocumentKind: "architectural" | "shop" | "schedule" | "product_spec";
        /**
         * DocumentRegistration
         * @description A document about to be uploaded: what it is, and the exact bytes it will be.
         *
         *     There is no size field. A declared size nothing compares against would read as a check and be
         *     none — the size recorded on the artifact is measured from the stored object at confirmation, which
         *     is a measurement rather than a claim. The hash is the one declaration, and it is the one that is
         *     checked.
         */
        DocumentRegistration: {
            /** @description What kind of source document this is, from the fixed V1 vocabulary. */
            kind: components["schemas"]["DocumentKind"];
            /**
             * Sha256
             * @description The SHA-256 of the file you are about to upload, lowercase hex. Hash it locally first. It is part of the storage key, so the upload ticket you get back permits writing exactly these bytes and nothing else.
             */
            sha256: string;
        };
        /**
         * DocumentVersionOut
         * @description One immutable upload, pinned to the exact bytes it represents.
         */
        DocumentVersionOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Page Count */
            page_count: number;
            /** Sha256 */
            sha256: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Source Artifact Id
             * Format: uuid
             */
            source_artifact_id: string;
            /** Storage Key */
            storage_key: string;
        };
        /**
         * EvidenceLocation
         * @description The immutable drawing location behind one operand.
         */
        EvidenceLocation: {
            /** Authority */
            authority: string;
            /**
             * Canonical Observation Id
             * Format: uuid
             */
            canonical_observation_id: string;
            /** Coordinate Space */
            coordinate_space: string;
            /** Crop Uri */
            crop_uri: string | null;
            /** Document Role */
            document_role: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /**
             * Page Id
             * Format: uuid
             */
            page_id: string;
            /** Page Index */
            page_index: number;
            /** Polygon */
            polygon: string[][];
            /** Semantic Type */
            semantic_type: string;
        };
        /**
         * ExactOperand
         * @description One exact operand, with evidence when it came from a drawing.
         */
        ExactOperand: {
            /** Denominator */
            denominator: string;
            evidence: components["schemas"]["EvidenceLocation"] | null;
            /** Evidence Status */
            evidence_status: string;
            /** Name */
            name: string;
            /** Numerator */
            numerator: string;
            /** Unit */
            unit: string;
        };
        /**
         * ExportSummary
         * @description Counts, so a consumer that ignores every flag still cannot report a clean package.
         *
         *     The per-finding label can be filtered out of a view. A total sitting at the top of the payload is
         *     harder to lose, and "42 findings, 39 of which abstained" is a sentence that stops somebody saying the
         *     drawings passed.
         */
        ExportSummary: {
            /** Abstentions */
            abstentions: number;
            /** By Outcome */
            by_outcome: {
                [key: string]: number;
            };
            /** Decisions */
            decisions: number;
            /** Findings */
            findings: number;
        };
        /**
         * ExportedFinding
         * @description One finding's full chain, with whether the engine actually decided anything.
         */
        ExportedFinding: {
            /** Abstained */
            abstained: boolean;
            chain: components["schemas"]["FindingChain"];
        };
        /**
         * FindingChain
         * @description Everything persisted to explain and recompute one finding.
         */
        FindingChain: {
            /** Engine Version */
            engine_version: string;
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Operands */
            operands: components["schemas"]["ExactOperand"][];
            /** Outcome */
            outcome: string;
            /** Parameter Versions */
            parameter_versions: {
                [key: string]: string;
            };
            rule_snapshot: components["schemas"]["RuleSnapshotRecord"];
            /** Severity */
            severity: string;
            /** Trace */
            trace: components["schemas"]["CalculationTraceOut"] | components["schemas"]["AbstentionTraceOut"] | components["schemas"]["OpaqueTraceOut"];
        };
        /**
         * FindingCounts
         * @description How a package's findings break down, for a list that has not opened one yet.
         *
         *     **Every outcome is named, and they sum to `total`.** A summary that reported only passes and
         *     failures would leave abstentions — `REVIEW_REQUIRED`, `NOT_FOUND`, `NO_APPLICABLE_RULE` — in
         *     neither column, and a reader would take the remainder for passes. Under V1's exact-match rule the
         *     abstention count is expected to be large, so hiding it would misrepresent the run.
         */
        FindingCounts: {
            /** Critical Failed */
            critical_failed: number;
            /** Failed */
            failed: number;
            /** No Applicable Rule */
            no_applicable_rule: number;
            /** Not Found */
            not_found: number;
            /** Passed */
            passed: number;
            /** Review Required */
            review_required: number;
            /** Total */
            total: number;
        };
        /**
         * FindingExportV1
         * @description The export envelope. Version first, so a consumer can check before it parses.
         */
        FindingExportV1: {
            /** Findings */
            findings: components["schemas"]["ExportedFinding"][];
            /**
             * Package Id
             * Format: uuid
             */
            package_id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /**
             * Schema Version
             * @constant
             */
            schema_version: "1";
            summary: components["schemas"]["ExportSummary"];
        };
        /**
         * FindingOut
         * @description One finding, with enough version information to go and reconstruct it.
         *
         *     Every version that could explain the result is here — the rule snapshot's content hash, the rule
         *     version, the engine build, the parameter sets in force. `AGENTS.md` §2.7: a finding that cannot
         *     be attributed to the versions that produced it is an assertion rather than a record.
         */
        FindingOut: {
            /**
             * Check Run Id
             * Format: uuid
             */
            check_run_id: string;
            /** Check Type */
            check_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Engine Version */
            engine_version: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            outcome: components["schemas"]["Outcome"];
            /**
             * Package Revision Id
             * Format: uuid
             */
            package_revision_id: string;
            /** Parameter Set Versions */
            parameter_set_versions: {
                [key: string]: string;
            };
            /** Product Type */
            product_type: string;
            reviewer_action?: components["schemas"]["ReviewerActionOut"] | null;
            /** Revision Number */
            revision_number: number;
            /** Rule Id */
            rule_id: string;
            /** Rule Snapshot Hash */
            rule_snapshot_hash: string;
            /**
             * Rule Snapshot Id
             * Format: uuid
             */
            rule_snapshot_id: string;
            /** Rule Version */
            rule_version: string;
            severity: components["schemas"]["Severity"];
        };
        /**
         * FindingPage
         * @description One page of findings, plus how to ask for the next one.
         *
         *     `next_cursor` is `None` when this is the last page — and that is the only way to know. A page
         *     shorter than `limit` is *not* a reliable end-of-list signal in any cursor scheme, and treating it
         *     as one is how a consumer stops early and reports a package as clean.
         */
        FindingPage: {
            /** Items */
            items: components["schemas"]["FindingOut"][];
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Ordering
             * @default Critical first, and within one severity the failures before the abstentions and the abstentions before the passes. Ties are broken by oldest first, then by id, so the order is total and a page boundary always falls in the same place. Full key: severity (CRITICAL, MAJOR, MINOR, ADVISORY), then outcome (FAIL, REVIEW_REQUIRED, NOT_FOUND, NO_APPLICABLE_RULE, PASS), then created_at ascending, then id ascending.
             */
            ordering: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * OpaqueTraceOut
         * @description A trace this API does not recognise, handed over intact.
         *
         *     **Not an error and not a silent empty object.** A recompute is compared against what the engine
         *     recorded, so dropping a shape nobody has taught this endpoint about would lose the only copy. A
         *     reader gets the content and is told plainly that it was not understood.
         */
        OpaqueTraceOut: {
            /** Content */
            content: {
                [key: string]: unknown;
            };
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "unrecognised";
        };
        /**
         * OpenReviewSession
         * @description Start reviewing one package revision.
         *
         *     Names the revision rather than the package: a package moves on, and a review that silently
         *     followed it would record decisions against drawings the reviewer never saw.
         */
        OpenReviewSession: {
            /**
             * Package Revision Id
             * Format: uuid
             */
            package_revision_id: string;
        };
        /**
         * OperationOut
         * @description One reviewed operation a rule may name, and the operands it takes.
         *
         *     This is a signature, not an implementation. A rule selects an operation by name from the typed
         *     registry (`AGENTS.md` §2.2); there is no field here, and none anywhere in the API, that could
         *     carry executable text.
         */
        OperationOut: {
            /**
             * Kind
             * @description `verdict` for an operation that decides an outcome, `derivation` for one that produces an intermediate value another operation consumes.
             */
            kind: string;
            /** Name */
            name: string;
            /**
             * Operands
             * @description Operand name to arity — `scalar` for one value, `list` for many.
             */
            operands: {
                [key: string]: string;
            };
            /** Version */
            version: string;
        };
        /**
         * Outcome
         * @description What a check concluded.
         *
         *     Only ``PASS`` and ``FAIL`` are decisions. The other three are honest abstentions, and
         *     the distinction matters: abstaining costs reviewer time, whereas a wrong ``PASS`` can be
         *     manufactured. See :func:`is_decision`.
         * @enum {string}
         */
        Outcome: "PASS" | "FAIL" | "NOT_FOUND" | "REVIEW_REQUIRED" | "NO_APPLICABLE_RULE";
        /**
         * PackageCreate
         * @description A new reviewable drawing package.
         */
        PackageCreate: {
            /**
             * Vendor
             * @description Who supplied the drawings, if it is known. Left null rather than guessed — an invented vendor name is worse than an absent one, because it reads as a fact.
             */
            vendor?: string | null;
        };
        /**
         * PackageOut
         * @description One package, and the revision documents currently attach to.
         *
         *     `current_revision_number` is returned rather than left to be inferred. A package has several
         *     revisions and a client that assumed "the latest" would eventually register a document against a
         *     superseded one (`docs/DESIGN_PLATFORM.md` §5).
         */
        PackageOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Current Revision Id
             * Format: uuid
             */
            current_revision_id: string;
            /** Current Revision Number */
            current_revision_number: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Project Id
             * Format: uuid
             */
            project_id: string;
            /** State */
            state: string;
            /** Vendor */
            vendor: string | null;
        };
        /**
         * PackagePage
         * @description One page of packages, plus how to ask for the next one.
         *
         *     `next_cursor` is `None` on the last page, and that is the only reliable end-of-list signal — a page
         *     shorter than `limit` is not one in any cursor scheme.
         */
        PackagePage: {
            /** Items */
            items: components["schemas"]["PackageOut"][];
            /** Limit */
            limit: number;
            /** Next Cursor */
            next_cursor?: string | null;
            /** Ordering */
            ordering: string;
        };
        /**
         * PresignedUpload
         * @description Where to send the bytes, how, and until when.
         *
         *     Replay `method` and `required_headers` exactly. On a backend that signs headers, the same bytes
         *     sent with a different verb or a different `Content-Type` is a different request and is refused —
         *     which is the ticket being narrow, not the storage being awkward.
         */
        PresignedUpload: {
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Method */
            method: string;
            /** Required Headers */
            required_headers: {
                [key: string]: string;
            };
            /** Storage Key */
            storage_key: string;
            /** Upload Url */
            upload_url: string;
        };
        /**
         * PublicationOut
         * @description What was published, by whom, and on what basis.
         *
         *     Carries the approver, the author and the regression summary because "was this approved?" is a
         *     weaker question than "who approved it, who wrote it, and what was it checked against?", and only
         *     the second is worth anything when a finding is disputed months later.
         */
        PublicationOut: {
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
            /** Approved By */
            approved_by: string;
            /** Author */
            author: string;
            /** Production Ready */
            production_ready: boolean;
            /** Rationale */
            rationale: string;
            /** Regression Summary */
            regression_summary: string;
            /** Release Note */
            release_note: string;
            /** Rule Id */
            rule_id: string;
            /** Snapshot Id */
            snapshot_id: string;
            target: components["schemas"]["PublicationTarget"];
            /** Unconfirmed Tolerances */
            unconfirmed_tolerances: number;
            /** Version */
            version: string;
        };
        /**
         * PublicationRequest
         * @description Which proposal is being approved, and what for.
         *
         *     It names a proposal rather than carrying one. Two reasons, and the second is the load-bearing
         *     one: no rule content crosses this boundary, so no tolerance a client typed can reach the
         *     rulebook; and naming the exact content hash means the approver approves the bytes they read,
         *     not whatever the proposal says by the time the request arrives.
         */
        PublicationRequest: {
            /**
             * Snapshot Id
             * @description The content hash of the proposal being approved — the `sha256:<hex>` it would publish as. Not a proposal id: the hash changes the moment the proposed rule does, so an approval cannot silently follow an edit.
             */
            snapshot_id: string;
            /** @description `development` for authoring and testing, where a placeholder tolerance is expected. `production` for real drawings, where every tolerance must be a client-supplied number — a rule with a placeholder is refused here (ADR-0011). */
            target: components["schemas"]["PublicationTarget"];
        };
        /**
         * PublicationTarget
         * @description Where a snapshot is being published to.
         *
         *     The distinction exists because `ADR-0011`'s readiness gate belongs at **release**, not at
         *     authoring. A rule carrying an unconfirmed tolerance should be authorable, reviewable and
         *     testable — that is what the `UNCONFIRMED` sentinel is *for*. What it must never do is reach
         *     production, where it looks like a working check while returning REVIEW REQUIRED for everything.
         * @enum {string}
         */
        PublicationTarget: "development" | "production";
        /**
         * RecordAction
         * @description One thing a reviewer did to one finding.
         *
         *     No `actor` and no `package_revision_id`. The actor is the authenticated caller, and the revision
         *     is read off the finding the server loaded — a caller cannot state which revision they were
         *     looking at, which is what makes the trail worth keeping.
         */
        RecordAction: {
            action: components["schemas"]["ReviewActionKind"];
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Note */
            note?: string | null;
        };
        /**
         * ReviewActionKind
         * @description What a reviewer did to a finding. Four verbs, and no fifth.
         *
         *     There is deliberately no `edit`. A reviewer either confirms what the system said, corrects the
         *     value it read, grants a bounded exception, or dismisses the finding — each of which leaves a
         *     different record. A general "edit" would collapse all four into one, and the ledger exists to
         *     keep them apart.
         * @enum {string}
         */
        ReviewActionKind: "confirm" | "correct" | "except" | "dismiss";
        /**
         * ReviewActionOut
         * @description A recorded action. Append-only — a changed mind is a second row, and the first one stays.
         */
        ReviewActionOut: {
            action: components["schemas"]["ReviewActionKind"];
            /** Actor */
            actor: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Note */
            note: string | null;
            /**
             * Package Revision Id
             * Format: uuid
             */
            package_revision_id: string;
            /**
             * Review Session Id
             * Format: uuid
             */
            review_session_id: string;
        };
        /**
         * ReviewSessionOut
         * @description A sitting of review work.
         */
        ReviewSessionOut: {
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Package Revision Id
             * Format: uuid
             */
            package_revision_id: string;
            /** Reviewer */
            reviewer: string;
        };
        /**
         * ReviewSessionPage
         * @description Sessions, newest first.
         */
        ReviewSessionPage: {
            /** Items */
            items: components["schemas"]["ReviewSessionOut"][];
        };
        /**
         * ReviewerActionOut
         * @description What a reviewer last did to a finding, so a reload does not undo their work.
         *
         *     **Why this is on the finding rather than fetched per session.** The actions ledger is
         *     append-only and keyed by session, which is right for the audit trail and wrong for the question
         *     a review screen asks: *has this finding been dealt with?* Without an answer the workspace showed
         *     every finding as untouched after a refresh, and a reviewer could — and did, in testing — record
         *     the same decision twice because the first one was invisible.
         *
         *     **It is the latest action by anyone, not by the caller.** A finding's disposition is a property
         *     of the package, not of whoever is looking: if a colleague confirmed it an hour ago, showing it as
         *     outstanding would invite a second opinion recorded as a first. `actor` says who, so the screen
         *     can show that it was somebody else.
         *
         *     A changed mind is a later row, never an edit, so "latest" is the whole state. The earlier rows
         *     remain in the ledger and are what an approval is reconstructed from.
         */
        ReviewerActionOut: {
            action: components["schemas"]["ReviewActionKind"];
            /** Actor */
            actor: string;
            /**
             * At
             * Format: date-time
             */
            at: string;
            /** Note */
            note?: string | null;
        };
        /**
         * RuleOut
         * @description One rule, as it stands today: its effective snapshot and whether it could be released.
         */
        RuleOut: {
            /** Check Type */
            check_type: string;
            /** Name */
            name: string;
            /** Product Type */
            product_type: string;
            /** Production Ready */
            production_ready: boolean;
            /**
             * Published Versions
             * @description How many snapshots exist for this rule, including superseded ones.
             */
            published_versions: number;
            /** Release Note */
            release_note: string;
            /** Rule Id */
            rule_id: string;
            /** Severity */
            severity: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Unconfirmed Tolerances */
            unconfirmed_tolerances: number;
            /** Version */
            version: string;
        };
        /**
         * RuleSnapshotOut
         * @description One published version of a rule, with everything needed to check what you were given.
         *
         *     `snapshot_id` is the content hash and `canonical_json` is the exact bytes it was computed from,
         *     so a client can recompute `sha256(canonical_json)` and compare. What that proves is narrow and
         *     worth stating: the bytes in this response are the bytes this identifier names. It is not a
         *     signature — anyone able to change the response could change both halves — and it says nothing
         *     about whether this is the snapshot that judged any particular drawing. That question is answered
         *     by comparing this identifier with the one on the finding.
         */
        RuleSnapshotOut: {
            /**
             * Canonical Json
             * @description The exact RFC 8785 bytes that were hashed. Returned in full rather than behind a second request because a hash you cannot check is a promise rather than a fact.
             */
            canonical_json: string;
            /**
             * Effective
             * @description Whether this is the version the resolver would pick today — the highest version of this rule. Older snapshots stay listed because findings cite them.
             */
            effective: boolean;
            /**
             * Production Ready
             * @description False when any tolerance in this rule is still a placeholder. Such a rule can be authored, reviewed and tested, and it can never produce a PASS or a FAIL.
             */
            production_ready: boolean;
            /**
             * Release Note
             * @description The same judgement as `production_ready`, in a sentence a person can act on.
             */
            release_note: string;
            /** Rule Id */
            rule_id: string;
            /**
             * Snapshot Id
             * @description The content hash, algorithm included — `sha256:<hex>`. Recompute it from `canonical_json` to confirm you received what this identifier names.
             */
            snapshot_id: string;
            /** Unconfirmed Tolerances */
            unconfirmed_tolerances: number;
            /** Version */
            version: string;
        };
        /**
         * RuleSnapshotRecord
         * @description The complete immutable rule content used by the check run.
         */
        RuleSnapshotRecord: {
            /** Canonical Json */
            canonical_json: string;
            /** Check Type */
            check_type: string;
            /**
             * Database Id
             * Format: uuid
             */
            database_id: string;
            /** Product Type */
            product_type: string;
            /** Rule Id */
            rule_id: string;
            /** Snapshot Id */
            snapshot_id: string;
            /** Version */
            version: string;
        };
        /**
         * Severity
         * @description How much a wrong answer on this check costs.
         *
         *     The primary release metric is the *critical* false-PASS rate, so without this the metric
         *     cannot be computed at all — nothing else records which checks are critical (D3).
         * @enum {string}
         */
        Severity: "CRITICAL" | "MAJOR" | "MINOR" | "ADVISORY";
        /**
         * ToleranceReportOut
         * @description How much of the rulebook is still waiting on a number from the client.
         *
         *     `report` is written to be pasted into an email unedited — that is the whole point of it, and
         *     `tests/api/test_rules_api.py` asserts on the wording rather than only on the counts.
         */
        ToleranceReportOut: {
            /** Awaiting Tolerance */
            awaiting_tolerance?: components["schemas"]["AwaitingToleranceOut"][];
            /** Blocked */
            blocked: number;
            /**
             * Can Release Anything
             * @description False when no rule in the rulebook could produce a PASS or a FAIL. Kept separate from `blocked` because 'some rules are waiting' and 'nothing works yet' are different conversations.
             */
            can_release_anything: boolean;
            /** Releasable */
            releasable: number;
            /** Report */
            report: string;
            /** Total Rules */
            total_rules: number;
        };
        /**
         * TracedOperandOut
         * @description One input to the calculation, as the engine recorded it.
         */
        TracedOperandOut: {
            /** Evidence Ref */
            evidence_ref?: string | null;
            /** Name */
            name: string;
            /** Source */
            source: string;
            /** Value */
            value: string;
        };
        /**
         * UploadConfirmation
         * @description Tell the API the bytes have landed, and what they were.
         *
         *     The hash is required and re-checked against the stored object. That is the whole substance of this
         *     request: the API cannot know an upload finished, and it will not take "it finished" on trust.
         */
        UploadConfirmation: {
            /**
             * Page Count
             * @description How many pages the file has. Your count, not ours — the API never opens the file. Ingestion builds the real page manifest and a disagreement shows up there.
             */
            page_count: number;
            /**
             * Sha256
             * @description The SHA-256 you declared at registration. The stored object is read and hashed, and a mismatch is rejected without writing anything.
             */
            sha256: string;
        };
        /**
         * UploadRequest
         * @description Another upload of an existing document — a new version of the same logical document.
         *
         *     Separate from `DocumentRegistration` because the document already exists and its `kind` is already
         *     settled. Sending `kind` again would let a caller appear to change it, and a document that silently
         *     changes kind is a document whose earlier versions were classified under something else.
         */
        UploadRequest: {
            /**
             * Sha256
             * @description The SHA-256 of the new file.
             */
            sha256: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_operations_api_v1_operations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OperationOut"][];
                };
            };
        };
    };
    read_accepted_work_api_v1_projects__project_id__accepted_work__accepted_work_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                accepted_work_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcceptedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_upload_api_v1_projects__project_id__documents__document_id__confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadConfirmation"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentVersionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_upload_api_v1_projects__project_id__documents__document_id__uploads_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UploadRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUpload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_packages_api_v1_projects__project_id__packages_get: {
        parameters: {
            query?: {
                /** @description The `next_cursor` from the previous page. */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackagePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_package_api_v1_projects__project_id__packages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PackageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_package_api_v1_projects__project_id__packages__package_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PackageOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_document_api_v1_projects__project_id__packages__package_id__documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                package_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DocumentRegistration"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignedUpload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_findings_api_v1_projects__project_id__packages__package_id__findings_get: {
        parameters: {
            query?: {
                /** @description Restrict to these outcomes. Omit for all of them, abstentions included — a list that quietly dropped REVIEW_REQUIRED would make a package look clean. */
                outcome?: components["schemas"]["Outcome"][] | null;
                /** @description Restrict to these severities. */
                severity?: components["schemas"]["Severity"][] | null;
                /** @description Restrict to rules of these check types, e.g. `internal`. */
                check_type?: string[] | null;
                /** @description Restrict to rules about these product types, e.g. `countertop`. */
                product_type?: string[] | null;
                /** @description The `next_cursor` from the previous page. */
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                package_id: string;
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_findings_api_v1_projects__project_id__packages__package_id__findings_export_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingExportV1"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    summarise_findings_api_v1_projects__project_id__packages__package_id__findings_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                package_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingCounts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finding_chain_api_v1_projects__project_id__packages__package_id__findings__finding_id__chain_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                package_id: string;
                finding_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FindingChain"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_review_session_api_v1_projects__project_id__packages__package_id__review_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                package_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OpenReviewSession"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_review_sessions_api_v1_projects__project_id__review_sessions_get: {
        parameters: {
            query?: {
                mine?: boolean;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSessionPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_review_action_api_v1_projects__project_id__review_sessions__review_session_id__actions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                review_session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecordAction"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewActionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_review_session_api_v1_projects__project_id__review_sessions__review_session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
                review_session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewSessionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleOut"][];
                };
            };
        };
    };
    read_tolerance_report_api_v1_rules_tolerance_report_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ToleranceReportOut"];
                };
            };
        };
    };
    read_applicability_api_v1_rules__rule_id__applicability_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicabilityOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_rule_api_v1_rules__rule_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublicationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_snapshots_api_v1_rules__rule_id__snapshots_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleSnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
